name: Crowdin i18n Upload Action
on:
  workflow_dispatch:
  push:
    branches:
      - crowdin-source

jobs:
  
  i18n-upload-curriculum-files:
    name: Learn
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: ./tools
        run: |
          cd ./formatter
          npm ci
          cd ../challenge-md-parser
          npm ci
          cd ../challenge-md-parser/mdx
          npm ci
          cd ../../crowdin
          npm ci

      - name: Annotate Curriculum Files
        uses: ./tools/crowdin/actions/annotate-curriculum-files

      - name: Crowdin Upload
        uses: crowdin/github-action@master
        # options: https://github.com/crowdin/github-action/blob/master/action.yml
        with:
          # uploads
          upload_sources: true
          upload_translations: false
          auto_approve_imported: false
          import_eq_suggestions: false

          # global options
          config: './curriculum/crowdin.yml'
          base_url: ${{ secrets.CROWDIN_BASE_URL_FCC }}

          # Uncomment below to debug
          # dryrun_action: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID_CURRICULUM }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_SERVICE_TOKEN }}

      - name: Hide Non-Translated Strings
        uses: ./tools/crowdin/actions/hide-non-translated-strings
        env:
          CROWDIN_API_URL: 'https://freecodecamp.crowdin.com/api/v2/'
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_SERVICE_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID_CURRICULUM }}